1 : o1.o 
	gcc -O2 o1.c -o o1
2 : o2.o 
	gcc -O2 o2.c -o o2
3 : o3.o
	gcc -O2 o3.c -o o3
4 : o4.o
	gcc -O2 o4.c -o o4
5 : o5.o
	gcc -O2 o5.c -o o5
6 : o6.o
	gcc -O2 o6.c -o o6
7 : o7.o
	gcc -O2 o7.c -o o7 -lm
